name: Build RSS Feed
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write # <--- WICHTIG, sonst kein Push möglich
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # Use PAT for write access if needed
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Aggregator
        run: python fetch_and_cache.py
      - name: Commit and push feed
        uses: EndBug/add-and-commit@v9
        with:
          add: 'cached_feed.xml feed_log.txt'
          message: 'Update aggregated feed [skip ci]'
          pull: '--rebase --autostash'
